### PR TITLE
Add Androidx86 icon

### PR DESCRIPTION
**Pull request by 04ELY**
An icon for Androidx86
There is an icon for  Phoenix OS(an Androidx86 fork) but nothing for original project. So I made one. :D

### CODE REVIEW

**Comment by 04ELY** [comment]
:|

**Comment by 04ELY** [comment]
I'm still waiting :(

**Comment by EvanPurkhiser** [comment]
Hi @04ELY, sorry for the delay.

Could you actually change the icon to use the same `#191919` gray, and make the text transparent?

Thanks!

**Comment by EvanPurkhiser** [comment]
Actually looks like the colors are already inconsistent, so `#1A1A1A` is fine, lets make the text transparent though :)

**Comment by 04ELY** [comment]
Hi! Actually i made this long long ago (and randomly) & if you have icon guidelines/color standards etc. I can remake 😅 but I'm not perfect at design..

**Comment by EvanPurkhiser** [comment]
It's good! I think 90% there, just some tiny tweaks let's keep the general look the same but just make the text a cutout (so it's transparent where the text is)

**Pull request closed without merging**
