### PR TITLE
Added an os icon for xubuntu

### PR DESCRIPTION
**Pull request by euc**

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
The edges look kind of jaggy. Do you happen to have one with better anti-aliasing?

Also, compared to the rest of the icons, this one seems quite large. Hare are two circular examples:

 * [Elementary OS](https://github.com/EvanPurkhiser/rEFInd-minimal/blob/master/icons/os_elementary.png)
 * [Ubuntu](https://github.com/EvanPurkhiser/rEFInd-minimal/blob/master/icons/os_ubuntu.png)

Thanks!

**Comment by euc** [comment]
Don't quite know what to do about the anti-aliasing, but my eyes don't see any difference between the new version and your two icon examples, hopefully your eyes don't see any either :wink:

**Comment by euc** [comment]
Wow, never mind! Just saw them in my browser, quite the difference! :stuck_out_tongue_winking_eye:

**Comment by EvanPurkhiser** [comment]
I found a nice SVG and converted without any aliasing using inkscape! Let me know if it looks good :+1:

**Pull request closed without merging**
