### PR TITLE
Added logo for Pop!_OS

### PR DESCRIPTION
**Pull request by olivercalder**
Added logo for Pop!_OS. Flat #202020 color with transparency fade at edges, image size 128x128 pixels, with logo 64x64 pixels and centered.

### CODE REVIEW

**Comment by Seltonu** [comment]
Was checking this project out and wondered about a PopOS icon. It looks great nice work, hope it gets approved

**Comment by baylessj** [comment]
I'm also using Pop and this theme, downloaded the icon for use on my system. Would love to see this get merged!

**Comment by EvanPurkhiser** [comment]
This PR or https://github.com/EvanPurkhiser/rEFInd-minimal/pull/61 🤔

**Comment by heymajor** [comment]
Well done!

**Pull request merged**
