### PR TITLE
Added themed icons for firmware, refind, unknown os, and about

### PR DESCRIPTION
**Pull request by theRealPadster**
I added some icons I made for booting to EFI, rEFInd, Unknown OS and the About screen.

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
Thanks! I will look at these tonight! :-)

**Comment by theRealPadster** [comment]
Did you have a chance to look? I matched the colour exactly, and icon style/size as close as possible, so they should be fine.

**Comment by EvanPurkhiser** [comment]
Sorry for the delay!

Here are my thoughts for this pull request at the moment:

 * I really like the `os_unknown` icon! it fits perfectly with the theme and looks great!

 * I wish refind had a nice icon, I think the little search-glass-spinny-arrow thing is kind of bland. Maybe we can do something to make it look a little nicer, perhaps the icon could be negative space inside of a gray circle like some of the other icons? 

 * I'm not sure what I want to do about the little menu icons. In #7 I merged some icons which were basically rotated versions of the shutdown icon. But I'm not sure they really make much sense. I'm kind of torn because your icons are much more logical.

   I'm thinking what might make sense here is to have the 'stylized' shutdown icon, where the icon really doesn't mean anything other than being a nice looking 'down' arrow, **and** a more logical shutdown icon, along with a good set of other tool menu icons that are simply disabled by default. These are a good start, but if I merge these I'll probably want to remove the exit and reset icons and replace those immediately as well.

Do you mind if I merge in a few parts of your PR first and decide what to do about the other icons in another issue?

**Comment by theRealPadster** [comment]
Sure, you can pick which ones you want for now. 
I tried the grey circle thing, and I don't think it turned out as well, to be honest. 
os_refind_mine_cutout
I like the simple aesthetics of the current shutdown icon, and the exit/reset ones work well with it. I've just been using the theme with those and it seems fine. You won't see the icons I've added unless you add them manually, so you could totally add in an alternate set of shutdown-type icons. 

Sure, open another issue and discuss there.

**Comment by EvanPurkhiser** [comment]
Sorry, I haven't forgotten about your PR!

I actually saw [this theme](http://munlik.deviantart.com/art/Regular-rEFInd-theme-512091944) here and really fell in love with the tool icons.

I've left a comment asking the author if he would mind if I included them in this theme.

**Comment by theRealPadster** [comment]
Those are really nice! The only thing is that the cog icon doesn't seem to fit for UEFI/firmware to me. At first I thought it was a settings menu for rEFInd.

**Comment by theRealPadster** [comment]
Bump. Looks like the author of the other theme is fine with you using some of his icons.

**Comment by EvanPurkhiser** [comment]
Thanks for the heads up. I added your unknown icon and the Refind OS icon from munlik's theme. 

Still trying to decide what to do about the function icons. I really like his, but I'm not sure they fit the theme.

**Comment by theRealPadster** [comment]
Sure, it's up to you about the function icons.

**Comment by EvanPurkhiser** [comment]
Sure I'll go ahead and close this and add an issue for better icons.

**Comment by EvanPurkhiser** [comment]
Thanks again for the contributions! :-)

**Comment by justinkb** [comment]
You could rotate the reset/shutdown/exit icons to a ">" for an icon for UEFI shell

">" looks like a shell prompt

**Pull request closed without merging**
