### PR TITLE
Move theme into themes folder instead of root

### LINKED ISSUE #24: Move theme into themes folder instead of root
I've just built a theme (heavily inspired by yours, great job btw) and to make the installation a bit neater, I'm reccomending people create a `themes` folder and put it in there. It would also allow people to have multiple themes installed, which could be easily switched between, without cluttering up the root rEFInd directory.

I know there's no official right or wrong place to put the theme but I feel like this method is a lot neater. Would you accept a PR to follow this directory pattern on your theme too?

### PR DESCRIPTION
**Pull request by lukechilds**
Resolves #24

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
This sounds great!

**Comment by EvanPurkhiser** [comment]
Could you update the example entries as well, since they specifically reference icons in the theme.

It would be amazing if you also opened a PR for the [`gh-pages`](https://github.com/EvanPurkhiser/rEFInd-minimal/tree/gh-pages) branch for the instructions there too :-)

**Comment by lukechilds** [comment]
Sorry, mad weekend, just seen this!

Glad you're game, I'll work on those changes when I get in from work :+1:

**Comment by EvanPurkhiser** [comment]
Thank you for your work on this! I will merge these later tonight when I get home from work, I just need to verify everything looks good!

**Comment by lukechilds** [comment]
No probs, thanks for the badass theme :+1:

**Comment by lukechilds** [comment]
Hey, did you get a chance to check this?

**Comment by EvanPurkhiser** [comment]
Sorry for the super long delay! looks good!

**Pull request merged**
